---
apiVersion: v1
kind: Namespace
metadata:
  name: hellopage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellopage
  namespace: hellopage
  labels:
    app: hellopage
  annotations:
    # https://docs.fluxcd.io/en/stable/references/automated-image-update.html
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellopage
  template:
    metadata:
      labels:
        app: hellopage
    spec:
      containers:
      - name: app
        image: gcr.io/int128-1313/github.com/int128/hellopage:dev-6d16b4d
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hellopage
  namespace: hellopage
  labels:
    app: hellopage
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: hellopage
